import Head from "next/head";

import { api } from "@/utils/api";
import Todo from "@/components/todo";
import CreateTodo from "@/components/create-todo";
import { ThemeToggle } from "@/components/theme-toggle";

export default function Home() {
  const { data } = api.todo.findAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative min-h-screen w-full bg-background p-10">
        <div className="my-4 flex flex-col gap-2">
          {data?.map((todo) => <Todo key={todo.id} todo={todo} />)}
        </div>
        <CreateTodo />
        <div className="fixed right-4 top-4">
          <ThemeToggle />
        </div>
      </main>
    </>
  );
}
