import CreateTodo from "@/components/create-todo";
import { ThemeToggle } from "@/components/theme-toggle";
import TodosServer from "@/components/todosServer";
import { db } from "@/server/db";
import { type Todo } from "@prisma/client";
import type { InferGetServerSidePropsType } from "next";
import Head from "next/head";

export const getServerSideProps = async () => {
  let data = await db.todo.findMany();

  //? This is a workaround to avoid the error:
  //?  ⨯ N [Error]: Error serializing `.data[0].createdAt` returned from `getServerSideProps` in "/ssr".
  data = JSON.parse(JSON.stringify(data)) as Todo[];

  return { props: { data } };
};

export default function Page({
  data,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative w-full bg-background p-10">
        <TodosServer data={data} />
        <CreateTodo />
        <div className="fixed right-4 top-4">
          <ThemeToggle />
        </div>
      </main>
    </>
  );
}
